# Generated by Django 5.0.6 on 2024-07-21 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0002_rename_subject_contact_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='name',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='contact',
            name='lastName',
            field=models.CharField(default='', max_length=255),
        ),
    ]
