# Generated by Django 5.0.6 on 2024-09-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Schoolapp', '0003_rename_name_contact_firstname_contact_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='action_taken',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('unattended', 'Unattended'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='unattended', max_length=20),
        ),
    ]
