# Generated by Django 5.0 on 2024-01-06 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('home_address', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('language_spoken', models.CharField(max_length=255)),
                ('country_of_citizenship', models.CharField(max_length=2)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('parent_full_name', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('parent_home_address', models.CharField(max_length=255)),
                ('previous_school_name', models.CharField(max_length=255)),
                ('previous_class', models.CharField(max_length=10)),
                ('previous_school_address', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('emergency_contact', models.CharField(max_length=255)),
                ('emergency_contact_number', models.CharField(max_length=15)),
                ('medical_conditions', models.CharField(max_length=255)),
                ('allergies', models.CharField(max_length=255)),
                ('disabilities', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('vaccinated', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
        ),
    ]
