# Generated by Django 4.2.9 on 2024-02-04 19:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Admissionapp', '0002_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_number',
            field=models.CharField(default=1, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='submission_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
