# Generated by Django 4.2.9 on 2024-02-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissionapp', '0003_student_admission_number_student_submission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
