# Generated by Django 4.2.9 on 2024-02-04 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admissionapp', '0004_alter_student_admission_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='submission_date',
            new_name='submit_date',
        ),
    ]
