# Generated by Django 5.0.6 on 2024-08-14 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissionapp', '0005_rename_submission_date_student_submit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='country_of_citizenship',
            field=models.CharField(max_length=255),
        ),
    ]
