# Generated by Django 5.0.6 on 2024-10-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admissionapp', '0007_admission_admissionlog_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='user_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
