# Generated by Django 5.1.5 on 2025-01-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='created_by_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='reference_number',
            field=models.CharField(blank=True, editable=False, max_length=8, null=True, unique=True),
        ),
    ]
