# Generated by Django 5.1.6 on 2025-02-15 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0002_jobpost_created_by_email_jobpost_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='applications_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
