# Generated by Django 5.1.5 on 2025-02-09 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobposting', '0002_jobpost_created_by_email_jobpost_reference_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='resumes/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('HIRED', 'Hired')], default='PENDING', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_title', models.CharField(blank=True, max_length=200, null=True)),
                ('job_reference_number', models.CharField(blank=True, max_length=8, null=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('educational_level', models.CharField(choices=[('HIGH_SCHOOL', 'High School'), ('ASSOCIATE', 'Associate Degree'), ('BACHELOR', "Bachelor's Degree"), ('MASTER', "Master's Degree"), ('PHD', 'PhD')], default='HIGH_SCHOOL', max_length=20)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobposting.jobpost')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-applied_at'],
                'unique_together': {('job_post', 'email')},
            },
        ),
    ]
