# Generated by Django 5.0.6 on 2024-09-01 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0010_customuser_role_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
