# Generated by Django 5.1.3 on 2024-12-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_google_account',
            field=models.BooleanField(default=False),
        ),
    ]
