# Generated by Django 5.1.6 on 2025-04-06 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0018_customuser_is_google_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='class_name',
            field=models.CharField(blank=True, choices=[('creche', 'Creche'), ('nursery', 'Nursery'), ('kg1', 'KG 1'), ('kg2', 'KG 2'), ('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('jhs1', 'JHS 1'), ('jhs2', 'JHS 2'), ('jhs3', 'JHS 3')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='index_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('principal', 'Principal'), ('staff', 'Staff'), ('student', 'Student')], max_length=10),
        ),
    ]
