# Generated by Django 5.2 on 2025-04-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0019_customuser_class_name_customuser_index_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='class_name',
            field=models.CharField(blank=True, choices=[('Creche', 'Creche'), ('Nursery', 'Nursery'), ('KG 1', 'KG 1'), ('KG 2', 'KG 2'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('JHS 1', 'JHS 1'), ('JHS 2', 'JHS 2'), ('JHS 3', 'JHS 3')], max_length=10, null=True),
        ),
    ]
