# Generated by Django 5.2 on 2026-03-23 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0020_alter_customuser_class_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('suffix', models.CharField(blank=True, default='', help_text='e.g. Jr., Sr., III', max_length=10)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('grandparent', 'Grandparent'), ('sibling', 'Sibling'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('other', 'Other')], max_length=20)),
                ('primary_phone', models.CharField(help_text='Primary mobile number with country code, e.g. +233241234567', max_length=20)),
                ('secondary_phone', models.CharField(blank=True, default='', help_text='Alternate mobile, home, or office number', max_length=20)),
                ('email', models.EmailField(blank=True, default='', help_text='Personal email for official communication and portal access', max_length=254)),
                ('street_address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('state_region', models.CharField(blank=True, default='', help_text='State, region, or province', max_length=100)),
                ('postal_code', models.CharField(blank=True, default='', max_length=20)),
                ('id_type', models.CharField(blank=True, choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('voters_id', "Voter's ID"), ('other', 'Other')], default='', max_length=20)),
                ('id_number', models.CharField(blank=True, default='', help_text='ID document number for legal guardianship verification', max_length=50)),
                ('is_primary_contact', models.BooleanField(default=False, help_text='Mark as the main contact for this student')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_primary_contact', 'last_name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('id_number', ''), _negated=True), fields=('student', 'id_type', 'id_number'), name='unique_guardian_id_per_student')],
            },
        ),
    ]
