# Generated by Django 5.0.6 on 2024-07-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('department', models.CharField(choices=[('Finance Department', 'Finance Department'), ('Admissions Department', 'Admissions Department'), ('Student Affairs', 'Student Affairs'), ('Human Resource Department', 'Human Resource Department'), ('Academics Department', 'Academics Department')], max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
