# Generated by Django 5.0.6 on 2024-08-10 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booking_date',
            field=models.CharField(max_length=20),
        ),
    ]
