# Generated by Django 5.0.6 on 2024-08-10 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservationapp', '0002_alter_reservation_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booking_date',
            field=models.CharField(max_length=90),
        ),
    ]
