# Generated by Django 5.0.6 on 2024-08-10 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservationapp', '0003_alter_reservation_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='booking_date',
            field=models.DateTimeField(),
        ),
    ]
