# Generated by Django 5.0.6 on 2024-09-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservationapp', '0006_reservation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='last_modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
