# Generated by Django 5.0.6 on 2024-09-22 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservationapp', '0007_reservation_last_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='last_modified_by',
            field=models.CharField(max_length=300),
        ),
    ]
