# Generated by Django 5.0.6 on 2024-09-22 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservationapp', '0009_alter_reservation_last_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='last_modified_by',
            field=models.CharField(blank=True, default='System', max_length=100, null=True),
        ),
    ]
