# Generated by Django 5.0.6 on 2024-09-22 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservationapp', '0012_alter_reservation_last_modified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='last_modified_by',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='modified_by_user',
        ),
    ]
