# Generated by Django 5.0.6 on 2024-09-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservationapp', '0014_reservation_last_modified_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
