# Generated by Django 5.0.6 on 2024-09-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservationapp', '0018_remove_reservationlog_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationlog',
            name='user_email',
            field=models.EmailField(blank=True, max_length=255),
        ),
    ]
