# Generated by Django 5.2 on 2025-08-17 00:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text="Academic year e.g., '2023-2024'", max_length=9)),
                ('class_name', models.CharField(choices=[('Creche', 'Creche'), ('Nursery', 'Nursery'), ('KG 1', 'KG 1'), ('KG 2', 'KG 2'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('JHS 1', 'JHS 1'), ('JHS 2', 'JHS 2'), ('JHS 3', 'JHS 3')], help_text='Class this billing applies to', max_length=10)),
                ('term', models.CharField(choices=[('first', 'First Term'), ('second', 'Second Term'), ('third', 'Third Term')], help_text='Academic term', max_length=10)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_billing_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('academic_year', 'class_name', 'term')},
            },
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('category', models.CharField(help_text='Category name (user-defined)', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_mandatory', models.BooleanField(default=True, help_text='Whether this fee is mandatory for all students')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_billing_items', to=settings.AUTH_USER_MODEL)),
                ('billing_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_items', to='student_billing.billingtemplate')),
            ],
            options={
                'ordering': ['category', 'item_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('previous_arrears', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding balance from previous terms', max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount applied to this bill', max_digits=10)),
                ('additional_charges', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Additional charges specific to this student', max_digits=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('overdue', 'Overdue')], default='pending', max_length=10)),
                ('generated_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('scheduled_date', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_amount_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('billing_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_billing.billingtemplate')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_student_bills', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_date'],
                'unique_together': {('student', 'billing_template')},
            },
        ),
    ]
