# Generated by Django 5.2 on 2025-08-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingitem',
            name='is_mandatory',
        ),
        migrations.RemoveField(
            model_name='billingtemplate',
            name='is_active',
        ),
        migrations.AddField(
            model_name='studentbill',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='studentbill',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
