# Generated by Django 5.2 on 2025-08-24 19:01

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0002_remove_billingitem_is_mandatory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbill',
            name='fine_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fine amount (if applicable)', max_digits=10),
        ),
        migrations.AddField(
            model_name='studentbill',
            name='fine_description',
            field=models.CharField(blank=True, help_text='Description of fine (if any)', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='StudentBillLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='student_billing.studentbill')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
