# Generated by Django 5.2 on 2025-08-31 10:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0003_studentbill_fine_amount_studentbill_fine_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='studentbill',
            name='additional_charges',
        ),
        migrations.RemoveField(
            model_name='studentbill',
            name='fine_amount',
        ),
        migrations.RemoveField(
            model_name='studentbill',
            name='fine_description',
        ),
        migrations.AlterField(
            model_name='studentbill',
            name='previous_arrears',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Outstanding balance from previous terms (auto-calculated)', max_digits=10),
        ),
        migrations.CreateModel(
            name='BillingItemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('user_first_name', models.CharField(max_length=50)),
                ('user_last_name', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('billing_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='student_billing.billingitem')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_payments', to=settings.AUTH_USER_MODEL)),
                ('student_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='student_billing.studentbill')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_custom_charges', to=settings.AUTH_USER_MODEL)),
                ('student_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_charges', to='student_billing.studentbill')),
            ],
            options={
                'ordering': ['charge_name'],
                'unique_together': {('student_bill', 'charge_name')},
            },
        ),
    ]
