# Generated by Django 5.2 on 2025-08-31 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0004_remove_billingitem_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customcharge',
            unique_together=set(),
        ),
    ]
