# Generated by Django 5.2 on 2025-09-01 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0005_alter_customcharge_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
    ]
