# Generated by Django 5.2 on 2025-10-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0006_alter_studentbill_bill_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbill',
            name='discount_approved_by',
            field=models.CharField(blank=True, help_text='Name of person who approved the discount (required when discount is applied)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentbill',
            name='discount_reason',
            field=models.TextField(blank=True, help_text='Reason for applying discount (required when discount is applied)', null=True),
        ),
    ]
