# Generated by Django 5.2 on 2025-10-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0007_studentbill_discount_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbill',
            name='discount_approved_by',
            field=models.CharField(blank=True, help_text='Person who approved the discount', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentbill',
            name='discount_reason',
            field=models.TextField(blank=True, help_text='Reason for applying discount', null=True),
        ),
    ]
