# Generated by Django 5.2 on 2025-11-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0008_alter_studentbill_discount_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbill',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Auto-generated PDF of the bill', null=True, upload_to='bills/pdfs/%Y/%m/'),
        ),
    ]
