# Generated by Django 5.2 on 2025-11-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0009_studentbill_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbill',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Auto-generated PDF bill', null=True, upload_to='student_bills/%Y/%m/'),
        ),
    ]
