# Generated by Django 5.2 on 2026-05-31 18:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0011_alter_paymentreceipt_receipt_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceiptRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount the student claims to have paid', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', max_length=50)),
                ('payment_reference', models.CharField(help_text='Transaction ID, cheque number, or any payment reference', max_length=200)),
                ('proof_of_payment', models.FileField(help_text='Image or PDF proof of payment', upload_to='payment_proofs/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=20)),
                ('review_comment', models.TextField(blank=True, help_text="Required when status is 'under_review' or 'rejected'", null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_receipt', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_request', to='student_billing.paymentreceipt')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_receipt_requests', to=settings.AUTH_USER_MODEL)),
                ('student_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_requests', to='student_billing.studentbill')),
                ('submitted_by', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_receipt_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceiptRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('marked_under_review', 'Marked Under Review'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('reset_to_pending', 'Reset to Pending'), ('status_changed', 'Status Changed')], max_length=30)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('actor_first_name', models.CharField(max_length=50)),
                ('actor_last_name', models.CharField(max_length=50)),
                ('actor_email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='student_billing.paymentreceiptrequest')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
