# Generated by Django 5.2 on 2026-05-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0012_paymentreceiptrequest_paymentreceiptrequestlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceiptrequestlog',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('marked_under_review', 'Marked Under Review'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('reset_to_pending', 'Reset to Pending'), ('status_changed', 'Status Changed'), ('revoked', 'Revoked')], max_length=30),
        ),
    ]
