# Generated by Django 5.2 on 2026-06-07 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0013_alter_paymentreceiptrequestlog_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymentreceipt',
            index=models.Index(fields=['student_bill'], name='student_bil_student_321097_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentreceiptrequest',
            index=models.Index(fields=['submitted_by', 'status'], name='student_bil_submitt_1d5c75_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbill',
            index=models.Index(fields=['student', 'generated_date'], name='student_bil_student_ca30a5_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbill',
            index=models.Index(fields=['billing_template'], name='student_bil_billing_670b17_idx'),
        ),
        migrations.AddIndex(
            model_name='studentbill',
            index=models.Index(fields=['student', 'status'], name='student_bil_student_4a012d_idx'),
        ),
    ]
