# Generated by Django 5.2 on 2026-06-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0014_paymentreceipt_student_bil_student_321097_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceiptrequest',
            name='phone_number',
            field=models.CharField(blank=True, default='', help_text='Phone number used for the payment (e.g. Mobile Money number)', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentreceiptrequestlog',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('marked_under_review', 'Marked Under Review'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('reset_to_pending', 'Reset to Pending'), ('status_changed', 'Status Changed'), ('revoked', 'Revoked'), ('corrected', 'Corrected by Staff')], max_length=30),
        ),
    ]
