# Generated by Django 5.2 on 2026-06-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0015_paymentreceiptrequest_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceiptrequest',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number used for the payment (e.g. Mobile Money number)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentreceiptrequestlog',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('marked_under_review', 'Marked Under Review'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('reset_to_pending', 'Reset to Pending'), ('status_changed', 'Status Changed'), ('revoked', 'Revoked')], max_length=30),
        ),
    ]
