# Generated by Django 5.2 on 2026-06-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0016_alter_paymentreceiptrequest_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceiptrequestlog',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('marked_under_review', 'Marked Under Review'), ('rejected', 'Rejected'), ('accepted', 'Accepted'), ('reset_to_pending', 'Reset to Pending'), ('status_changed', 'Status Changed'), ('revoked', 'Revoked'), ('amount_changed', 'Amount Changed'), ('payment_method_changed', 'Payment Method Changed'), ('payment_reference_changed', 'Payment Reference Changed'), ('phone_number_changed', 'Phone Number Changed'), ('review_comment_changed', 'Review Comment Changed')], max_length=30),
        ),
    ]
