# Generated by Django 5.2 on 2026-06-14 00:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0017_alter_paymentreceiptrequestlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentbill',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('paid', 'Fully Paid'), ('overpaid', 'Overpaid (Credit)'), ('overdue', 'Overdue')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentbill',
            name='previous_arrears',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Net balance carried forward from previous terms. Negative value means the student has a credit.', max_digits=10),
        ),
    ]
