# Generated by Django 5.2 on 2026-06-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0018_alter_studentbill_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingtemplate',
            name='academic_year',
            field=models.CharField(help_text="Academic year e.g., '2024-2025'", max_length=9),
        ),
        migrations.AlterField(
            model_name='paymentreceiptrequest',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number used for the payment', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentreceiptrequest',
            name='review_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentbill',
            name='discount_approved_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='studentbill',
            name='discount_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
