# Generated by Django 5.2 on 2026-06-27 18:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_billing', '0019_alter_billingtemplate_academic_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbill',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='studentbill',
            index=models.Index(fields=['status', 'published_at'], name='student_bil_status_ba9ba7_idx'),
        ),
    ]
