# Generated by Django 5.0.6 on 2024-11-02 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0002_emaillist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='emails',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
