# Generated by Django 5.0.6 on 2024-11-03 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Subscriptions', '0003_alter_emaillist_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillist',
            name='emails',
            field=models.TextField(),
        ),
    ]
