# Generated by Django 5.2 on 2026-04-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultsEntry', '0006_result_report_card_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='classcourse',
            name='teacher_email',
            field=models.EmailField(default='staff@school.edu', help_text='Email address of the course teacher', max_length=254),
        ),
        migrations.AddField(
            model_name='classcourse',
            name='teacher_name',
            field=models.CharField(default='Staff Name', help_text='Full name of the course teacher', max_length=150),
        ),
        migrations.AddField(
            model_name='classcourse',
            name='teacher_phone',
            field=models.CharField(default='0000000000', help_text='Phone number of the course teacher', max_length=20),
        ),
    ]
