# Generated by Django 5.0.6 on 2024-09-03 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0024_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('principal', 'Principal'), ('staff', 'Staff')], default='staff', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='admin_auth.customprofile')),
            ],
            options={
                'verbose_name': 'Custom Profile',
                'verbose_name_plural': 'Custom Profiles',
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
