# Generated by Django 5.0.6 on 2024-09-07 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0028_customuser_role_alter_customuser_groups_and_more'),
        ('authapp', '0012_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCustomUser',
            fields=[
            ],
            options={
                'verbose_name': 'Admin Custom User',
                'verbose_name_plural': 'Admin Custom Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authapp.customuser',),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
