# Generated by Django 5.2 on 2025-04-18 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentclasshistory',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentclasshistory',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentclasshistory',
            name='student',
        ),
        migrations.AlterModelOptions(
            name='academicyear',
            options={'ordering': ['-start_date'], 'verbose_name_plural': 'Academic Years'},
        ),
        migrations.AlterModelOptions(
            name='booklistitem',
            options={'ordering': ['order', 'name']},
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='academicyear',
            name='updated_at',
        ),
        migrations.AlterUniqueTogether(
            name='booklist',
            unique_together={('academic_year', 'class_name')},
        ),
        migrations.RemoveField(
            model_name='booklistitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='booklistitem',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='booklist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booklist',
            name='publish_date',
            field=models.DateTimeField(blank=True, help_text='Date when scheduled book list will be published', null=True),
        ),
        migrations.AddField(
            model_name='booklist',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='booklistitem',
            name='book_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='booklist.booklist'),
        ),
        migrations.AddField(
            model_name='booklistitem',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Whether this item is required or optional'),
        ),
        migrations.AddField(
            model_name='booklistitem',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which items appear'),
        ),
        migrations.AddField(
            model_name='booklistitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(help_text="Academic year (e.g., '2024-2025')", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='class_name',
            field=models.CharField(choices=[('creche', 'Creche'), ('nursery', 'Nursery'), ('kg1', 'KG 1'), ('kg2', 'KG 2'), ('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('jhs1', 'JHS 1'), ('jhs2', 'JHS 2'), ('jhs3', 'JHS 3')], help_text='Class this book list is for', max_length=10),
        ),
        migrations.DeleteModel(
            name='BookListEntry',
        ),
        migrations.DeleteModel(
            name='StudentClassHistory',
        ),
        migrations.RemoveField(
            model_name='booklist',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='booklist',
            name='publication_date',
        ),
    ]
