# Generated by Django 5.2 on 2025-04-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0003_remove_booklist_publish_date_booklist_scheduled_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='publish_date',
            field=models.DateTimeField(blank=True, help_text='Date when book list was actually published', null=True),
        ),
    ]
