# Generated by Django 5.2 on 2025-04-20 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0005_studentclasshistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentclasshistory',
            unique_together=set(),
        ),
    ]
