# Generated by Django 5.2 on 2025-04-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booklist', '0006_alter_studentclasshistory_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclasshistory',
            name='academic_year',
            field=models.CharField(help_text="Academic year (e.g., '2024-2025')", max_length=20),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='academic_year',
            field=models.CharField(help_text="Academic year (e.g., '2024-2025')", max_length=20),
        ),
        migrations.AlterModelOptions(
            name='booklist',
            options={'ordering': ['-created_at', 'class_name']},
        ),
        migrations.AlterModelOptions(
            name='studentclasshistory',
            options={'ordering': ['-academic_year']},
        ),
        migrations.AlterField(
            model_name='booklist',
            name='class_name',
            field=models.CharField(choices=[('Creche', 'Creche'), ('Nursery', 'Nursery'), ('KG 1', 'KG 1'), ('KG 2', 'KG 2'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('JHS 1', 'JHS 1'), ('JHS 2', 'JHS 2'), ('JHS 3', 'JHS 3')], help_text='Class this book list is for', max_length=10),
        ),
        migrations.AlterField(
            model_name='studentclasshistory',
            name='class_name',
            field=models.CharField(choices=[('Creche', 'Creche'), ('Nursery', 'Nursery'), ('KG 1', 'KG 1'), ('KG 2', 'KG 2'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3'), ('Class 4', 'Class 4'), ('Class 5', 'Class 5'), ('Class 6', 'Class 6'), ('JHS 1', 'JHS 1'), ('JHS 2', 'JHS 2'), ('JHS 3', 'JHS 3')], max_length=10),
        ),
        migrations.DeleteModel(
            name='AcademicYear',
        ),
    ]
