# Generated by Django 5.0.6 on 2024-08-20 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_ticket_id'),
    ]

    operations = [
    ]
