# Generated by Django 5.0.6 on 2024-08-20 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_set_unique_ticket_id'),
    ]

    operations = [
    ]
