# Generated by Django 5.0.6 on 2024-10-13 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticketlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_id',
            new_name='TicketID',
        ),
    ]
