# Generated by Django 5.0.6 on 2024-10-13 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_rename_ticket_id_ticket_ticketid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketlog',
            name='reservation',
        ),
        migrations.AddField(
            model_name='ticketlog',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tickets.ticket'),
            preserve_default=False,
        ),
    ]
